### ISSUE TITLE
[BUG] Can't use nested args in mutations with TypeScript

### ISSUE THREAD

**Issue by screendriver** [khaosdoctor/gotql#25]
**Describe the bug**

In your README you mention that you can use nested objects:

```js
const mutation = {
  operation {
    name: 'addLog',
    args: {
      logType: { value: 'status_change', escape: false}, // Enum Value
      fromState: variables.fromState,
      toState: variables.toState,
      idUser: variables.idUser,
      idCampaign: variables.idCampaign,
      owner: {
        ownerType: variables.ownerType,
        username: variables.username,
        picture: variables.picture,
        name: variables.name,
        id: variables.id
      }
    },
    fields: [ 'uuid' ]
  }
}
```

But when you use TypeScript in your project this is not possible because `args` is defined as

```ts
args?: {
  [name: string]: string | ArgObject;
};

export declare type ArgObject = {
    value: string;
    escape: boolean;
};
```

That means that that you can't set objects as value (like `owner` in your example). Only strings or objects with `{ value: '', escape: true/false }` are allowed.

**To Reproduce**
1. Use TypeScript and try to create a mutation with a nested object.

**Current behavior**
Does not compile.

**Expected behavior**
Should compile.

**Comment by khaosdoctor** [comment]
Can you please test if it's working?

Thanks for your help :D

**Comment by screendriver** [comment]
It works now from a compiler perspective 👍 

But now I get a

```sh
Runner error: Error when executing query: Parse error: Failed to parse operation "myTest" => varName.indexOf is not a function
    at Object.<anonymous> (/Users/me/project/node_modules/gotql/dist/modules/runner.js:122:19)
```

**Comment by khaosdoctor** [comment]
@screendriver Please fill in another issue with the JSON-like query and the query you obtain when it’s parsed,  it looks like a variable issue, not an arg one

**Comment by screendriver** [comment]
Done: https://github.com/khaosdoctor/gotql/issues/28
