### ISSUE TITLE
response.statusCode should be a Number

### ISSUE THREAD

**Issue by franciscolourenco** [khaosdoctor/gotql#34]
**Describe the bug**
`response.statusCode` is a String, but it should be a Number. All the libraries I've used so far use numbers for status codes, including nodejs.
https://nodejs.org/api/http.html#http_response_statuscode

**To Reproduce**
Make a request with `gotql.query()` and examinine the `statusCode` property of the response.

**Current behavior**
`typeof response.statusCode === 'string'`

**Expected behavior**
`typeof response.statusCode === 'number'`

**Comment by khaosdoctor** [comment]
Strange, there's a test for it asserting deep equally that it's a `500`, will look into it

**Comment by khaosdoctor** [comment]
Currently, the status code is typed as `number` as per the interface below: 

https://github.com/khaosdoctor/gotql/blob/056de85fea20d1fe64ca1f519b808e284640879b/src/types/UserOptions.ts#L10

Also, `got` types its responses as `number` and TypeScript is typing it as number:

![image](https://user-images.githubusercontent.com/3200560/80771793-eaa83180-8b2a-11ea-988f-2e3466699f33.png)

And Got too:

![image](https://user-images.githubusercontent.com/3200560/80771814-fa277a80-8b2a-11ea-82a2-7c71f6ce7bce.png)

I wasn't able to reproduce this error, can you please provide an example?

**Comment by franciscolourenco** [comment]
Can't reproduce it anymore either, thanks!
