### ISSUE TITLE
Arrays in args are treated as objects

### ISSUE THREAD

**Issue by franciscolourenco** [khaosdoctor/gotql#35]
Arrays nested inside args are translated as objects
 
**To Reproduce**
```js
gotQl.mutation(
  process.env.GRAPHQL_HOST,
  {
    operation: {
      name: 'insert_example',
      args: {
        objects: {id, status, price},
        on_conflict: {constraint: 'example_pkey', update_columns: ['status', 'price']},
      },
      fields: ['affected_rows'],
    }
  },
)
```

**Current behavior**
Resulting query contains:
```js
update_columns: { 0: "status", 1: "price" }
```

**Expected behavior**
Resulting query contains:
```js
update_columns: ["status", "price"]

```

**Comment by khaosdoctor** [comment]
True, taking a look here, this will take a while, though... I hope to finish this week since I have a lot of work

**Comment by khaosdoctor** [comment]
Finally found the issue here, I wasn't testing it properly
