### ISSUE TITLE
Seems to choke on boolean argument values

### ISSUE THREAD

**Issue by NetOperatorWibby** [khaosdoctor/gotql#4]
**Describe the bug**
While parsing a query with a boolean argument it fails and I see:

```
Error: Parse error: Failed to parse operation "WHATEVER" => varName.indexOf is not a function
```

**To Reproduce**
1. Create a query with a boolean argument
2. Try to parse it
3. Feel sad

**Expected behavior**
I expected to see my query succeed.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version: Latest

**Additional context**
This is a great module, thanks for creating it.

**Comment by khaosdoctor** [comment]
Hey man! I'm really sorry, Github did not notified me about this issue so I didn't see it...

Well, since it's been a while, I don't think you'd have the query you wrote, right? :D

However I'll dig into it ASAP

**Comment by NetOperatorWibby** [comment]
Yeah, I don't remember what the query was. I just [forked it](https://git.inc.sh/IdeasNeverCease/gotql) and fixed the issue myself.

**Comment by khaosdoctor** [comment]
Yeah! I'll try to look up to your solution and update the code here! Thanks!

**Comment by khaosdoctor** [comment]
Thanks @NetOperatorWibby! Managed to find and fix it :) Hope you're linking this module!

**Comment by franciscolourenco** [comment]
Think this still might be an issue with `null` value arguments

**Comment by khaosdoctor** [comment]
The problem with #33 is not actually the `null` value, it's some sort of parsing problem in the parser itself, but it crashes before the `null`. Probably because it is identifying the object as a variable
