### ISSUE TITLE
[BUG] Empty objects for args and variables are not handled properly

### ISSUE THREAD

**Issue by pigulla** [khaosdoctor/gotql#51]
**Describe the bug**
gotql does not handle empty objects for `args` and `variables` properly, the handling should be semantically identical to the values being absent, i.e. `undefined`. The relevant LoC are in [getQueryVars](https://github.com/khaosdoctor/gotql/blob/24ddd1060172cfedd53a1b6c31f1ff7048192696/src/modules/parser.ts#L22) and [parseOperation](https://github.com/khaosdoctor/gotql/blob/24ddd1060172cfedd53a1b6c31f1ff7048192696/src/modules/parser.ts#L239).

**Bug in getQueryVars()**

***To Reproduce***
```javascript
parse({
    name: 'TestQuery',
    operation: {
        name: 'TestOp',
        fields: ['field1', 'field2']
    },
    variables: {}
}, 'query'));
```

***Current behavior***
Return value is: `query TestQuery ) { TestOp { field1 field2 } }`

***Expected behavior***
Return value should be: `query TestQuery { TestOp { field1 field2 } }`

**Bug in parseOperation()**

***To Reproduce***
```javascript
parse({
    name: 'TestQuery',
    operation: {
        name: 'TestOp',
        args: {},
        fields: ['field1', 'field2']
    }
}, 'query'));
```

***Current behavior***
Return value is: `query TestQuery { TestOp() { field1 field2 } }`

***Expected behavior***
Return value should be: `query TestQuery { TestOp { field1 field2 } }`

**Comment by khaosdoctor** [comment]
Thanks for the issue! I'm checking it right now!
