### ISSUE TITLE
[BUG] Query is not parsed correctly for where:{ _and :[] }

### ISSUE THREAD

**Issue by mesudip** [khaosdoctor/gotql#53]
Am i  missing something
```js
gotql.parser(
    {
        operation: {
            name: "Metadata",
            args: {
                where: {
                    _and: [
                        { hash: { _in: ['a','b'] } }
                        ,{pool:{ _eq:32}}
                        ]
                }
            },
            fields: ["key", "value"]
        }
    },
    'query'
)
```

`>>> query { Metadata(where: { _and: ["[object Object]", "[object Object]"] }) { key value } }`

**Comment by mesudip** [comment]
https://github.com/khaosdoctor/gotql/blob/a90261909c6abed5b9e8fb26d8eada6998a086a4/src/modules/parser.ts#L195

This is the culprit line. I couldn't do it due to Type mismatch errors. Typescript is beyond me.

**Comment by khaosdoctor** [comment]
Sorry about the delay, had a very busy month. I'm taking care of this today.
